[versions]
activity-compose = "1.11.0"
agp = "8.12.0"
androidx-test-core-ktx = "1.7.0"
androidx-test-ext-junit = "1.3.0"
compose-bom = "2025.09.00"
barcode-scanning = "17.3.0"
camera-core = "1.5.0"
camera-mlkit-vision = "1.4.2"
coil-compose = "2.7.0"
converter-gson = "3.0.0"
core-ktx = "1.17.0"
dagger-hilt = "2.57.1"
espresso-core = "3.7.0"
firebase-bom = "34.1.0"
firebase-crashlytics-gradle = "3.0.6"
google-services = "4.4.3"
guava = "33.4.8-jre"
hilt-common = "1.2.0"
junit = "4.13.2"
junit-jupiter = "5.13.4"
kotlin = "2.2.10"
ksp = "2.2.20-2.0.3"
lifecycle-runtime-ktx = "2.9.4"
mockito = "5.18.0"
mockito-kotlin = "6.0.0"
mockk = "1.14.5"
navigation-compose = "2.9.3"
opencsv = "5.12.0"
paparazzi = "2.0.0-alpha02"
retrofit = "3.0.0"
robolectric = "4.15.1"
room = "2.8.0"
splashscreen = "1.0.1"
test-rules = "1.7.0"
test-runner = "1.7.0"
uiautomator = "2.3.0"
work-runtime-ktx = "2.10.3"

[libraries]
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera-core" }
androidx-camera-core = { module = "androidx.camera:camera-core", version.ref = "camera-core" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera-core" }
androidx-camera-mlkit-vision = { module = "androidx.camera:camera-mlkit-vision", version.ref = "camera-mlkit-vision" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera-core" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hilt-common" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-common" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcode-scanning" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "converter-gson" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger-hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-hilt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics"}
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics"}
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
mockito-core = { group = "org.mockito", name = "mockito-core", version.ref = "mockito" }
mockito-kotlin = { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito-kotlin" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
opencsv = { module = "com.opencsv:opencsv", version.ref = "opencsv" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core-ktx" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }

[plugins]
app-cash-paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi"}
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = {id = "com.android.library", version.ref = "agp"}
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt"}
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[bundles]