[versions]
accompanist-systemuicontroller = "0.32.0"
activity-compose = "1.8.2"
agp = "8.2.0"
androidx-test-core-ktx = "1.5.0"
androidx-test-ext-junit = "1.1.5"
compose-bom = "2023.10.01"
core-ktx = "1.12.0"
dagger-hilt = "2.50"
espresso-core = "3.5.1"
firebase-bom = "32.7.0"
firebase-crashlytics-gradle = "2.9.9"
google-services = "4.4.0"
hilt-common = "1.1.0"
junit = "4.13.2"
junit-jupiter = "5.8.1"
ksp = "1.9.21-1.0.16"
lifecycle-runtime-ktx = "2.6.2"
navigation-compose = "2.7.6"
org-jetbrains-kotlin-android = "1.9.21"
paparazzi = "1.3.1"
room = "2.6.1"
test-rules = "1.5.0"
test-runner = "1.5.2"
ui-test-junit4 = "1.5.4"
uiautomator = "2.2.0"
work-runtime-ktx = "2.8.1"
splashscreen = "1.0.1"
org-jetbrains-kotlin-jvm = "1.9.21"

[libraries]
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist-systemuicontroller" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
androidx-hilt-common = { module = "androidx.hilt:hilt-common", version.ref = "hilt-common" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-common" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { group = "androidx.room", name = "room-testing", version.ref = "room" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "test-rules" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "test-runner" }
androidx-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "uiautomator" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
dagger = { module = "com.google.dagger:dagger", version.ref = "dagger-hilt" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-hilt" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx"}
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx"}
firebase-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "firebase-crashlytics-gradle" }
google-services = { module = "com.google.gms:google-services", version.ref = "google-services" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger-hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger-hilt" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin-android" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
material3 = { group = "androidx.compose.material3", name = "material3" }
runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
test-core-ktx = { module = "androidx.test:core-ktx", version.ref = "androidx-test-core-ktx" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4", version.ref = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview", version="1.6.0-beta03"}
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

[plugins]
app-cash-paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi"}
com-android-application = { id = "com.android.application", version.ref = "agp" }
com-android-library = {id = "com.android.library", version.ref = "agp"}
com-google-dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt"}
com-google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp"}
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "org-jetbrains-kotlin-android" }
org-jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "org-jetbrains-kotlin-jvm" }

[bundles]